services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - 8081:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
