services:
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        environment:
            - SSL_MODE=off
            - PHP_OPCACHE_ENABLE=1
        networks:
            - app-network
        ports:
            - 8081:8080
networks:
    app-network:
        driver: bridge
