services:
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        environment:
            - SSL_MODE=off
            - PHP_OPCACHE_ENABLE=1
        networks:
            - app-network
        ports:
            - 8081:8080

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        networks:
            - app-network
        volumes:
            - ./mysql-data:/var/lib/mysql

networks:
    app-network:
        driver: bridge
